name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dataclutch/requirements.txt

      - name: Create tarball
        run: |
          mkdir -p build
          tar -czvf build/dataclutch.tar.gz -C dataclutch .

      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: dataclutch-tarball
          path: build/dataclutch.tar.gz